scalar Date

type Bookings {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  phone: String!
  software: String!
  company: String!
  address: String!
  createdAt: Date!
}

query getBookings {
  bookings {
    firstName
    lastName
    email
    phone
    company
    software
    address
    createdAt
  }
}

query getBooking($email: String!) {
  booking(email: $email) {
    firstName
    lastName
    email
    phone
    company
    software
    address
    createdAt
  }
}

type Query {
  bookings: [Bookings!]!
  booking(email: String!): [Bookings!]!
}
